apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    dc: UK
  template:
    metadata:
      name: mysvcpod
      labels:
        dc: UK
    spec:
      containers:
        - name: mycont
          image: vimal13/apache-webserver-php
